import type { Metadata } from "next";
import { Montserrat, Baskervville } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
  fallback: ["Arial"],
});

const baskervville = Baskervville({
  display: "swap",
  adjustFontFallback: true,
  weight: "400",
  variable: "--font-baskervville",
  subsets: ["latin"],
  fallback: ["Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body className={`${montserrat.variable} ${baskervville.variable}`}>
        {children}
      </body>
    </html>
  );
}
